# Generated by Django 5.2.1 on 2025-05-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_userlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
