# Generated by Django 5.2.1 on 2025-06-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldName', models.CharField(blank=True, max_length=200, null=True)),
                ('FieldType', models.CharField(blank=True, max_length=200, null=True)),
                ('FieldValidation', models.CharField(blank=True, max_length=100, null=True)),
                ('RequiredCheck', models.CharField(blank=True, max_length=100, null=True)),
                ('Priority', models.IntegerField(blank=True, null=True)),
                ('fieldNumber', models.IntegerField(blank=True, null=True)),
                ('ClientId', models.IntegerField(blank=True, null=True)),
                ('CreateDate', models.DateTimeField(blank=True, null=True)),
                ('FieldStatus', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'field_master',
            },
        ),
        migrations.CreateModel(
            name='FieldMasterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldValueName', models.CharField(blank=True, max_length=300, null=True)),
                ('ClientId', models.CharField(blank=True, max_length=20, null=True)),
                ('FieldStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('FieldId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapp.fieldmaster')),
            ],
            options={
                'db_table': 'field_master_value',
            },
        ),
    ]
