# Generated by Django 5.2.1 on 2025-06-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_fieldmaster_fieldmastervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmastervalue',
            name='FieldId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='crmapp.fieldmaster'),
        ),
    ]
