# Generated by Django 5.2.1 on 2025-06-18 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_dynamicformdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('calling_number', models.CharField(blank=True, max_length=15, null=True)),
                ('enquiry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiry_source', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_enquiry_source', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_date', models.DateField(blank=True, null=True)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('calling_status', models.CharField(blank=True, max_length=100, null=True)),
                ('interested_status', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_calling_status', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_sub_calling_status', models.CharField(blank=True, max_length=100, null=True)),
                ('select_bus', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=100, null=True)),
                ('construction_level', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alternative_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_product', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('order_description', models.TextField(blank=True, null=True)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('registration_status', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('seller_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_table',
            },
        ),
    ]
