# Generated by Django 5.2.1 on 2025-06-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_brandtable_zonetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_mt', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_inr', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_team_remarks', models.TextField(blank=True, null=True)),
                ('lead_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_final_remarks_reformat', models.TextField(blank=True, null=True)),
                ('lead_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('product_value', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_info', to=settings.AUTH_USER_MODEL)),
                ('lead_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_table', to='crmapp.leadtable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_info_table',
            },
        ),
    ]
