# Generated by Django 5.2.1 on 2025-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_salesinfotable'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtable',
            name='secure_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
