# Generated by Django 5.2.1 on 2025-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_contactdetails_leadtable_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonetable',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zonetable',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
