# Generated by Django 5.2.1 on 2025-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_zonetable_district_zonetable_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city_custom', models.CharField(max_length=100)),
                ('l1_name', models.CharField(max_length=100)),
                ('l1_mail', models.EmailField(max_length=150)),
                ('l1_mobile', models.CharField(max_length=20)),
                ('l2_name', models.CharField(max_length=100)),
                ('l2_mail', models.EmailField(max_length=150)),
                ('l2_mobile', models.CharField(max_length=20)),
                ('l3_mail', models.EmailField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_contact',
            },
        ),
    ]
