# Generated by Django 5.2.1 on 2025-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_salescontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_sub_type', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition_1', models.CharField(blank=True, max_length=100, null=True)),
                ('disposition_2', models.CharField(blank=True, max_length=100, null=True)),
                ('follow_up_time', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
