# Generated by Django 5.2.1 on 2025-06-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0020_tblfollowup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesVOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_status', models.CharField(max_length=100)),
                ('connection_status', models.CharField(max_length=100)),
                ('sales_person_voc', models.TextField()),
                ('followup_for', models.TextField()),
            ],
            options={
                'db_table': 'sales_voc',
            },
        ),
    ]
