# Generated by Django 5.2.1 on 2025-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_salesvoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblfollowup',
            name='sales_voc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
