# Generated by Django 5.2.1 on 2025-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_tblfollowup_sales_voc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='callback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='callback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
