# Generated by Django 5.2.1 on 2025-07-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0023_historylead_callback_time_leadtable_callback_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblfollowup',
            name='followup_status',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='tblfollowup',
            name='followup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
