# Generated by Django 5.2.1 on 2025-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_tblfollowup_followup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='lead_closer_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='lead_closer_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
