# Generated by Django 5.2.1 on 2025-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_historylead_lead_closer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='username',
            field=models.CharField(default='unknown_username', max_length=150),
        ),
    ]
