# Generated by Django 5.2.1 on 2025-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0026_userlist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='username',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
