# Generated by Django 5.2.1 on 2025-07-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0027_alter_userlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='seller_email_id_L2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historylead',
            name='seller_phone_no_L2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='seller_email_id_L2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='seller_phone_no_L2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
