# Generated by Django 5.2.1 on 2025-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0028_historylead_seller_email_id_l2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserAssignmentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'adviser_assignment_tracker',
            },
        ),
    ]
