# Generated by Django 5.2.1 on 2025-08-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0029_adviserassignmenttracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='lead_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historylead',
            name='lead_closer_status_new',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='lead_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='lead_closer_status_new',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
