# Generated by Django 5.2.1 on 2025-09-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0030_historylead_lead_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='final_lead_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='final_lead_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
