# Generated by Django 5.2.1 on 2025-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0031_historylead_final_lead_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylead',
            name='lead_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historylead',
            name='lead_upload_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='lead_action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadtable',
            name='lead_upload_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
