# Generated by Django 5.2.1 on 2025-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0032_historylead_lead_action_historylead_lead_upload_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='inbound_outbound',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
