# Generated by Django 5.2.1 on 2025-12-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0033_userlist_inbound_outbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='historysalesinfo',
            name='sales_person_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesinfotable',
            name='sales_person_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
