# Generated by Django 5.2.1 on 2025-12-25 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0034_historysalesinfo_sales_person_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDiaryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_diary_counter', to='crmapp.leadtable')),
            ],
            options={
                'db_table': 'sales_diary_counter',
            },
        ),
    ]
