# Generated by Django 5.2.1 on 2025-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0035_salesdiarycounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylead',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leadtable',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
