# Generated by Django 5.2.1 on 2026-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0036_alter_historylead_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadtable',
            name='dialer_lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
