# Generated by Django 5.2.1 on 2026-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0037_leadtable_dialer_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallyzerCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True)),
                ('emp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_number', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('call_type', models.CharField(blank=True, max_length=50, null=True)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('call_recording_url', models.TextField(blank=True, null=True)),
                ('crm_status', models.CharField(blank=True, max_length=255, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
