# Generated by Django 5.2.1 on 2026-07-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0038_callyzercalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTimeDetailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date_start', models.DateField(db_index=True)),
                ('report_date_end', models.DateField(db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('calls', models.IntegerField(default=0)),
                ('time_clock_sec', models.IntegerField(default=0)),
                ('login_time_sec', models.IntegerField(default=0)),
                ('wait_sec', models.IntegerField(default=0)),
                ('wait_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('talk_sec', models.IntegerField(default=0)),
                ('talk_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dispo_sec', models.IntegerField(default=0)),
                ('dispo_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pause_sec', models.IntegerField(default=0)),
                ('pause_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dead_sec', models.IntegerField(default=0)),
                ('dead_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('customer_sec', models.IntegerField(default=0)),
                ('login_clock_time', models.CharField(blank=True, max_length=8)),
                ('logout_clock_time', models.CharField(blank=True, max_length=8)),
                ('acht_sec', models.IntegerField(default=0)),
                ('extra_stats', models.JSONField(blank=True, default=dict)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_time_detail_report',
                'indexes': [models.Index(fields=['report_date_start', 'report_date_end'], name='agent_time__report__a835b7_idx')],
                'unique_together': {('report_date_start', 'report_date_end', 'user_id')},
            },
        ),
    ]
