# Generated by Django 5.2.1 on 2026-09-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0039_agenttimedetailreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date_start', models.DateField(db_index=True)),
                ('report_date_end', models.DateField(db_index=True)),
                ('uniqueid', models.CharField(blank=True, max_length=60)),
                ('nuniqueid', models.CharField(blank=True, max_length=60)),
                ('lead_id', models.CharField(blank=True, default='', max_length=20)),
                ('agent', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_status', models.CharField(blank=True, max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('length_in_sec', models.IntegerField(default=0)),
                ('length_in_min', models.CharField(blank=True, max_length=12)),
                ('campaign_id', models.CharField(blank=True, max_length=50)),
                ('term_reason', models.CharField(blank=True, max_length=50)),
                ('pulled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdr_report',
                'indexes': [models.Index(fields=['report_date_start', 'report_date_end'], name='cdr_report_report__381b79_idx'), models.Index(fields=['call_date'], name='cdr_report_call_da_21c7d2_idx'), models.Index(fields=['agent'], name='cdr_report_agent_3c49f4_idx')],
            },
        ),
    ]
